// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6665.NunsandBolts.subsystems;

import org.usfirst.frc6665.NunsandBolts.RobotMap;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Collector extends Subsystem {
	private Spark motor;

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
	public Collector(){
		motor = new Spark(RobotMap.COLLECTOR_MOTOR);
	}
	
	@Override
	protected void initDefaultCommand(){}
	
	public void collect(){
		motor.set(1);
	}
	
	public void stop(){
		motor.set(0);
	}

	public void eject(){
		motor.set(-1);
	}

}

