// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6665.NunsandBolts;


import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {

    public static SpeedController driveTrainSpeedController1;
    public static SpeedController driveTrainSpeedController2;
    public static SpeedController driveTrainSpeedController3;
    public static SpeedController driveTrainSpeedController4;
    public static RobotDrive driveTrainRobotDrive41;

	public static final int SHOOTER_MOTOR = 1; //Shooter Motor PWM Channel
	public static final int FEEDER_MOTOR = 2; //Feeder Motor PWM Channel
	public static final int AGITATOR_MOTOR = 3; //agitator motor 1 PWM channel
	public static final int COLLECTOR_MOTOR = 4; //Collector Motor PWM Channel

	public static final int LEFT_FRONT_MOTOR = 5; //Left Front Drive Motor PWM Channel
	public static final int LEFT_BACK_MOTOR = 6; //Left Back Drive Motor PWM Channel
	
	public static final int RIGHT_FRONT_MOTOR = 7; //Right Front Drive Motor PWM Channel
	public static final int RIGHT_BACK_MOTOR = 8; //Right Back Drive Motor PWM Channel
	
	public static double collectSetIn = 1.0;
	public static double collectSetOut = -1.0;
	
	public static double feederSpeed;
	public static double agitatorSpeed;

    public static void init() {

        driveTrainSpeedController1 = new Spark(LEFT_FRONT_MOTOR);
        LiveWindow.addActuator("DriveTrain", "Left Front Motor", (Spark) driveTrainSpeedController1);
        
        driveTrainSpeedController2 = new Spark(LEFT_BACK_MOTOR);
        LiveWindow.addActuator("DriveTrain", "Left Back Motor", (Spark) driveTrainSpeedController2);
        
        driveTrainSpeedController3 = new Spark(RIGHT_FRONT_MOTOR);
        LiveWindow.addActuator("DriveTrain", "Right Front Motor", (Spark) driveTrainSpeedController3);
        
        driveTrainSpeedController4 = new Spark(RIGHT_BACK_MOTOR);
        LiveWindow.addActuator("DriveTrain", "Right Back Motor", (Spark) driveTrainSpeedController4);
        
        driveTrainRobotDrive41 = new RobotDrive(driveTrainSpeedController1, driveTrainSpeedController2,
              driveTrainSpeedController3, driveTrainSpeedController4);
        
        driveTrainRobotDrive41.setSafetyEnabled(true);
        driveTrainRobotDrive41.setExpiration(0.1);
        driveTrainRobotDrive41.setSensitivity(0.5);
        driveTrainRobotDrive41.setMaxOutput(1.0);



    }
}
